### ISSUE TITLE
your package

### ISSUE THREAD

**Issue by Gon20000** [sandro-pasquali/day#1]
**Why would you make a package when you don't know how to use a constructor** (line 3) and really that's weird description 'about the day'

**Comment by ShayBox** [comment]
The package is 6 years old, code has changed since then man.

**Comment by Gon20000** [comment]
oh lmao you are right

**Comment by sandro-pasquali** [comment]
@Pharaoh2007 tell me more about line 3. I'd love to help.

**Comment by Gon20000** [comment]
it should be new Date()
constructors ends with ()

**Comment by Gon20000** [comment]
@sandro-pasquali

**Comment by sandro-pasquali** [comment]
@Pharaoh2007 Ah, as I suspected. The ECMA spec allows omitting parentheses. Linters often have default settings to enforce parens, for consistency (which I don't disagree with), but it isn't technically necessary. Sort of a "semicolons aren't necessary" situation...

**Comment by Gon20000** [comment]
I don't know if you're still there but sorry for that, no idea what I had in mind back then and I'd be thankful if you accept this apology!
